/**
 * Swagger Ecommerce - OpenAPI 3.0
 * Projet ecommerce sneakers Ephec 2TI Berlanger Clément Dylan Feron  Loic Dero Thibault Delime
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * objet chaussure
 */
export interface Chaussure { 
    /**
     * nom de la chaussure
     */
    nom: string;
    /**
     * prix de la chaussure
     */
    prix: number;
    /**
     * marque de la chaussure
     */
    marque: string;
}