/**
 * Swagger Ecommerce - OpenAPI 3.0
 * Projet ecommerce sneakers Ephec 2TI Berlanger Clément Dylan Feron  Loic Dero Thibault Delime
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * informations a propos d'une erreur
 */
export interface ErrorInfo { 
    /**
     * moment auquel l'erreur arrive sur le serveur
     */
    timestamp: Date;
    /**
     * message d'erreur pour l'utilisateur
     */
    message: string;
    /**
     * message d'erreur technique pour debugger
     */
    erreurTechnique: string;
}