/**
 * Swagger Ecommerce - OpenAPI 3.0
 * Projet ecommerce sneakers Ephec 2TI Berlanger Clément Dylan Feron  Loic Dero Thibault Delime
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Chaussure } from './chaussure';

/**
 * liste des chaussures disponibles
 */
export interface ListeChaussures { 
    /**
     * nombre de chaussures dans la liste
     */
    nombreChaussure: number;
    /**
     * tableau d'objet chaussure
     */
    chaussures: Array<Chaussure>;
}